//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ifrit.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ifrit.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ///1&lt;Geezard
        ///2&lt;Fungar
        ///3&lt;Bite Bug
        ///4&lt;Red Bat
        ///5&lt;Blobra
        ///6&lt;Gayla
        ///7&lt;Gesper
        ///8&lt;Fastitocalon-F
        ///9&lt;Blood Soul
        ///A&lt;Caterchipillar
        ///B&lt;Cockatrice
        ///C&lt;Grat
        ///D&lt;Buel
        ///E&lt;Mesmerize
        ///F&lt;Glacial Eyed
        ///10&lt;Belhelmel
        ///11&lt;Thrustaevis
        ///12&lt;Anacondaur
        ///13&lt;Creeps
        ///14&lt;Grendel
        ///15&lt;Jelleye
        ///16&lt;Grand Mantis
        ///17&lt;Forbidden
        ///18&lt;Armadodo
        ///19&lt;TriFace
        ///1A&lt;Fastitcalon
        ///1B&lt;Snow Lion
        ///1C&lt;Ochu
        ///1D&lt;SAM08G
        ///1E&lt;Death Claw
        ///1F&lt;Cactaur
        ///20&lt;Tonberry
        ///21&lt;Abyss Worm
        ///22&lt;Turtapod
        ///23&lt;Vysage
        ///24&lt;T-Rexaur
        ///25&lt;Bomb
        ///26&lt;Blitz
        ///27&lt;Wendigo
        ///28&lt;Torama
        ///29&lt;Imp
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string cards {
            get {
                return ResourceManager.GetString("cards", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0&lt;HP Recovery
        ///1&lt;Full HP Recovery
        ///2&lt;HP &amp; Status Rec.
        ///3&lt;Damage &amp; Zombie
        ///4&lt;Damage(m) &amp; Poison
        ///5&lt;Damage &amp; Dark
        ///6&lt;Damage(s) &amp; Poison
        ///7&lt;Damage
        ///8&lt;Dmg&amp;Random Status
        ///9&lt;No Change
        ///A&lt;Strength +1
        ///B&lt;Defense +1
        ///C&lt;Magic +1
        ///D&lt;Spirit +1
        ///E&lt;Speed +1
        ///F&lt;Max HP +10
        ///10&lt;??????
        ///11&lt;??????
        ///12&lt;??????
        ///13&lt;??????
        ///14&lt;??????
        ///15&lt;??????
        ///16&lt;??????
        ///17&lt;??????
        ///18&lt;??????
        ///19&lt;??????
        ///1A&lt;??????
        ///1B&lt;??????
        ///1C&lt;??????
        ///1D&lt;??????
        ///1E&lt;??????
        ///1F&lt;??????
        ///20&lt;??????
        ///21&lt;??????
        ///22&lt;??????
        ///23&lt;??????
        ///24&lt;??????
        ///25&lt;??????
        ///26&lt;??????
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string devour {
            get {
                return ResourceManager.GetString("devour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ffviii_ifrit {
            get {
                object obj = ResourceManager.GetObject("ffviii_ifrit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap ffviii_ifrit_real {
            get {
                object obj = ResourceManager.GetObject("ffviii_ifrit_real", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon ffviiiEnemy {
            get {
                object obj = ResourceManager.GetObject("ffviiiEnemy", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Folder_16x16 {
            get {
                object obj = ResourceManager.GetObject("Folder_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Help_16x16 {
            get {
                object obj = ResourceManager.GetObject("Help_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Information_16x16 {
            get {
                object obj = ResourceManager.GetObject("Information_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0&lt;Nothing
        ///1&lt;Potion
        ///2&lt;Potion&amp;
        ///3&lt;Hi-Potion
        ///4&lt;Hi-Potion&amp;
        ///5&lt;X-Potion
        ///6&lt;Mega-Potion
        ///7&lt;Phoenix Down
        ///8&lt;Mega Phoenix
        ///9&lt;Elixir
        ///A&lt;Megalixir
        ///B&lt;Antidote
        ///C&lt;Soft
        ///D&lt;Eye Drops
        ///E&lt;Echo Screen
        ///F&lt;Holy Water
        ///10&lt;Remedy
        ///11&lt;Remedy&amp;
        ///12&lt;Hero-trial
        ///13&lt;Hero
        ///14&lt;Holy War-trial
        ///15&lt;Holy War
        ///16&lt;Shell Stone
        ///17&lt;Protect Stone
        ///18&lt;Aura Stone
        ///19&lt;Death Stone
        ///1A&lt;Holy Stone
        ///1B&lt;Flare Stone
        ///1C&lt;Meteor Stone
        ///1D&lt;Ultima Stone
        ///1E&lt;Gysahl Greens
        ///1F&lt;Phoenix Pinion
        ///20&lt;Friendship
        ///21&lt;Tent
        ///22&lt;Pet House
        ///23&lt;Cottage
        ///24&lt;G-Potion
        /// [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string items {
            get {
                return ResourceManager.GetString("items", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Log_Out_16x16 {
            get {
                object obj = ResourceManager.GetObject("Log_Out_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 0&lt;Nothing
        ///1&lt;Fire
        ///2&lt;Fira
        ///3&lt;Firaga
        ///4&lt;Blizzard
        ///5&lt;Blizzara
        ///6&lt;Blizzaga
        ///7&lt;Thunder
        ///8&lt;Thundara
        ///9&lt;Thundaga
        ///A&lt;Water
        ///B&lt;Aero
        ///C&lt;Bio
        ///D&lt;Demi
        ///E&lt;Holy
        ///F&lt;Flare
        ///10&lt;Meteor
        ///11&lt;Quake
        ///12&lt;Tornado
        ///13&lt;Ultima
        ///14&lt;Apocalypse
        ///15&lt;Cure
        ///16&lt;Cura
        ///17&lt;Curaga
        ///18&lt;Life
        ///19&lt;Full-life
        ///1A&lt;Regen
        ///1B&lt;Esuna
        ///1C&lt;Dispel
        ///1D&lt;Protect
        ///1E&lt;Shell
        ///1F&lt;Reflect
        ///20&lt;Aura
        ///21&lt;Double
        ///22&lt;Triple
        ///23&lt;Haste
        ///24&lt;Slow
        ///25&lt;Stop
        ///26&lt;Blind
        ///27&lt;Confuse
        ///28&lt;Sleep
        ///29&lt;Silence
        ///2A&lt;Break
        ///2B&lt;Death
        ///2C&lt;Drain
        ///2D&lt;Pain
        ///2E&lt;Berserk
        ///2F&lt;Float
        ///30&lt;Zombie
        ///31&lt;M [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string magic {
            get {
                return ResourceManager.GetString("magic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Open_24x24 {
            get {
                object obj = ResourceManager.GetObject("Open_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Save_24x24 {
            get {
                object obj = ResourceManager.GetObject("Save_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02=\n
        ///0E=&lt;$&gt;
        ///20= 
        ///21=0
        ///22=1
        ///23=2
        ///24=3
        ///25=4
        ///26=5
        ///27=6
        ///28=7
        ///29=8
        ///2A=9
        ///2B=%
        ///2C=/
        ///2D=:
        ///2E=!
        ///2F=?
        ///30=...
        ///31=+
        ///32=-
        ///33==
        ///34=*
        ///35=&amp;
        ///36=jap &quot;
        ///37=jap&quot;
        ///38=(
        ///39=)
        ///3A=[&apos; in middle]
        ///3B=.
        ///3C=,
        ///3D=~
        ///3E=&quot;
        ///3F=&quot;
        ///40=&apos;
        ///41=#
        ///42=$
        ///43=`
        ///44=_
        ///45=A
        ///46=B
        ///47=C
        ///48=D
        ///49=E
        ///4A=F
        ///4B=G
        ///4C=H
        ///4D=I
        ///4E=J
        ///4F=K
        ///50=L
        ///51=M
        ///52=N
        ///53=O
        ///54=P
        ///55=Q
        ///56=R
        ///57=S
        ///58=T
        ///59=U
        ///5A=V
        ///5B=W
        ///5C=X
        ///5D=Y
        ///5E=Z
        ///5F=a
        ///60=b
        ///61=c
        ///62=d
        ///63=e
        ///64=f
        ///65=g
        ///66=h
        ///67=i
        ///68=j
        ///69=k
        ///6A=l
        ///6B=m
        ///6C=n
        ///6D=o
        ///6E=p
        ///6F [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textformat {
            get {
                return ResourceManager.GetString("textformat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 02=\n
        ///0E=&lt;$&gt;
        ///20= 
        ///21=0
        ///22=1
        ///23=2
        ///24=3
        ///25=4
        ///26=5
        ///27=6
        ///28=7
        ///29=8
        ///2A=9
        ///2B=%
        ///2C=/
        ///2D=:
        ///2E=!
        ///2F=?
        ///30=...
        ///31=+
        ///32=-
        ///33==
        ///34=*
        ///35=&amp;
        ///36=「
        ///37=」
        ///38=(
        ///39=)
        ///3A=·
        ///3B=.
        ///3C=,
        ///3D=~
        ///3E=»
        ///3F=«
        ///40=`
        ///41=#
        ///42=$
        ///43=&apos;
        ///44=_
        ///45=Α
        ///46=Β
        ///47=Ψ
        ///48=Δ
        ///49=Ε
        ///4A=Φ
        ///4B=Γ
        ///4C=H
        ///4D=I
        ///4E=Ξ
        ///4F=Κ
        ///50=Λ
        ///51=M
        ///52=N
        ///53=O
        ///54=Π
        ///55=:
        ///56=Ρ
        ///57=Σ
        ///58=Τ
        ///59=Θ
        ///5A=Ω
        ///5B=ς
        ///5C=Χ
        ///5D=Υ
        ///5E=Ζ
        ///5F=α
        ///60=β
        ///61=ψ
        ///62=δ
        ///63=ε
        ///64=φ
        ///65=γ
        ///66=η
        ///67=ι
        ///68=ξ
        ///69=κ
        ///6A=λ
        ///6B=μ
        ///6C=ν
        ///6D=ο
        ///6E=π
        ///6F=;
        ///70=ρ
        ///71=σ
        ///72= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string textformat_greek {
            get {
                return ResourceManager.GetString("textformat_greek", resourceCulture);
            }
        }
    }
}
